apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-deployments
  namespace: openshift-gitops
spec:
  destination:
    namespace: deployment-demos
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo3
    repoURL: https://github.com/helo/advanced_deployment_demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true