apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: code-quality-analysis
  namespace: deployment-demos
spec:
  steps:
    - command:
        - /bin/bash
        - '-c'
        - sleep 15
      image: registry.redhat.io/ubi7/ubi-minimal
      name: ''
      resources: {}
